### ISSUE TITLE
Error: zod_1.default.toJSONSchema is not a function

### ISSUE THREAD

**Issue by codenoid** [browser-use/browser-use-node#32]
hello, I'm having this error while trying to call `client.tasks.run({` with schema using zod

**Comment by maticzav** [comment]
Hi @codenoid 👋 

Thank you for opening the issue! Could you also share the version of `zod` you currently have installed?

**Comment by codenoid** [comment]
my yarn monorepo module was having version 3.x.x, but after updating to 4.x.x, the error is still exist, and when I update the import to explicitly load v4, its working #33
